### ISSUE TITLE
Crash after a few days of running

### ISSUE THREAD

**Issue by nohn** [spacemanspiff2007/sml2mqtt#2]
I'm running sml2mqtt on a Raspi 2. This night, it crashed:

```
[2021-10-12 22:09:47,985] [sml.device.ttyUSB0     ] ERROR    | Traceback (most recent call last):
[2021-10-12 22:09:47,988] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/sml2mqtt/sml_device.py", line 90, in read
[2021-10-12 22:09:47,990] [sml.device.ttyUSB0     ] ERROR    |     for sml_obj in frame.get_obis():
[2021-10-12 22:09:47,992] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/smllib/sml_frame.py", line 113, in get_obis
[2021-10-12 22:09:47,995] [sml.device.ttyUSB0     ] ERROR    |     ret.append(SmlListEntry.from_list(data))
[2021-10-12 22:09:47,997] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/smllib/sml_fields.py", line 146, in from_list
[2021-10-12 22:09:47,999] [sml.device.ttyUSB0     ] ERROR    |     raise ValueError('value is required!')
[2021-10-12 22:09:48,001] [sml.device.ttyUSB0     ] ERROR    | ValueError: value is required!
[2021-10-12 22:09:48,004] [sml.device.ttyUSB0     ] INFO     | ERROR
[2021-10-12 22:09:48,017] [sml.serial             ] INFO     | Port /dev/ttyUSB0 was closed
[2021-10-12 22:09:48,020] [sml.device.ttyUSB0     ] INFO     | PORT_CLOSED
[2021-10-12 22:09:48,217] [asyncio                ] ERROR    | Task was destroyed but it is pending!
task: <Task pending name='Task-170900' coro=<stop_loop() done, defined at /opt/sml2mqtt/venv/lib/python3.9/site-packages/sml2mqtt/_signals.py:10> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0xb5c3d838>()]>>
```

syslog doesn't contain anything interesting.

**Comment by spacemanspiff2007** [comment]
I've added a frame dump when an error occurs.
Could you update to the latest version and observe the logs and report back with the frame please?

**Comment by nohn** [comment]
Sure, I'll do.

**Comment by spacemanspiff2007** [comment]
Hm - I'll check the mqtt issue first. Maybe I can include the reconnect in the new version, too.
Would it be possible that you replace the sources in site-packages?

**Comment by nohn** [comment]
Apparently the workaround in #3 does not work. Only explanation I have is that in case of this exception, the application exits with return code 0. Could that be possible?

**Comment by spacemanspiff2007** [comment]
I've made an update which should fix the mqtt reconnect issue and reworked some of the shutdown logic.
The app should now properly exit with != 0 on error. Could you try again?

**Comment by mrumpf** [comment]
I have another error every few hours which stops sml2mqtt from reporting any values, but it does seems that the process does not exit and thus systemd not restarting the service:
````
[2022-01-25 04:50:45,423] [sml.device.ttyUSB0     ] ERROR    | Traceback (most recent call last):
[2022-01-25 04:50:45,424] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/sml2mqtt/sml_device.py", line 90, in read
[2022-01-25 04:50:45,425] [sml.device.ttyUSB0     ] ERROR    |     for sml_obj in frame.get_obis():
[2022-01-25 04:50:45,425] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 112, in get_obis
[2022-01-25 04:50:45,426] [sml.device.ttyUSB0     ] ERROR    |     self._parse_msg(data)
[2022-01-25 04:50:45,426] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 101, in _parse_msg
[2022-01-25 04:50:45,427] [sml.device.ttyUSB0     ] ERROR    |     self._parse_msg(v)
[2022-01-25 04:50:45,427] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 99, in _parse_msg
[2022-01-25 04:50:45,428] [sml.device.ttyUSB0     ] ERROR    |     parent_obj[i] = v = self.get_value()
[2022-01-25 04:50:45,428] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 62, in get_value
[2022-01-25 04:50:45,429] [sml.device.ttyUSB0     ] ERROR    |     raise InvalidBufferPos(f'Pos bigger than buffer: {e_pos} > {self.buf_len}')
[2022-01-25 04:50:45,429] [sml.device.ttyUSB0     ] ERROR    | smllib.sml_frame.InvalidBufferPos: Pos bigger than buffer: 941 > 219
[2022-01-25 04:50:45,430] [sml.device.ttyUSB0     ] INFO     | ERROR
[2022-01-25 04:50:45,434] [sml.serial             ] INFO     | Port /dev/ttyUSB0 was closed
[2022-01-25 04:50:45,434] [sml.device.ttyUSB0     ] INFO     | PORT_CLOSED
[2022-01-25 04:50:45,749] [asyncio                ] ERROR    | Task was destroyed but it is pending!
task: <Task pending name='Task-124577' coro=<stop_loop() done, defined at /opt/sml2mqtt/venv/lib/python3.8/site-packages/sml2mqtt/_signals.py:10> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x75b69550>()]>>
````

**Comment by spacemanspiff2007** [comment]
I just fixed an issue in the smllib but I have not yet ported it back to the sml2mqtt application.
Would you mind sharing the frame (redact your personal information) just so I can make sure this is not another issue?

Nonetheless the application should exit properly ...

**Comment by mrumpf** [comment]
Will the frame be dumped with debug logging turned on or how can I get hold of the frame that causes the issue?

**Comment by spacemanspiff2007** [comment]
Yes - it should be right above the Traceback you posted

**Comment by mrumpf** [comment]
Hm, there is nothing in the log. Here is the log with some more context:
````
... snipped ...
[2022-01-25 00:28:03,543] [sml.mqtt               ] ERROR    | [code:4] The client is not currently connected.
[2022-01-25 00:28:04,545] [sml.mqtt               ] ERROR    | [code:4] The client is not currently connected.
[2022-01-25 00:28:05,019] [sml2mqtt               ] INFO     | Shutting down ...
[2022-01-25 00:28:06,727] [sml.device.ttyUSB0     ] INFO     | PORT_OPENED
[2022-01-25 00:28:07,542] [sml.device.ttyUSB0     ] INFO     | OK

[2022-01-25 04:50:45,423] [sml.device.ttyUSB0     ] ERROR    | Traceback (most recent call last):
[2022-01-25 04:50:45,424] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/sml2mqtt/sml_device.py", line 90, in read
[2022-01-25 04:50:45,425] [sml.device.ttyUSB0     ] ERROR    |     for sml_obj in frame.get_obis():
[2022-01-25 04:50:45,425] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 112, in get_obis
[2022-01-25 04:50:45,426] [sml.device.ttyUSB0     ] ERROR    |     self._parse_msg(data)
[2022-01-25 04:50:45,426] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 101, in _parse_msg
[2022-01-25 04:50:45,427] [sml.device.ttyUSB0     ] ERROR    |     self._parse_msg(v)
[2022-01-25 04:50:45,427] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 99, in _parse_msg
[2022-01-25 04:50:45,428] [sml.device.ttyUSB0     ] ERROR    |     parent_obj[i] = v = self.get_value()
[2022-01-25 04:50:45,428] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 62, in get_value
[2022-01-25 04:50:45,429] [sml.device.ttyUSB0     ] ERROR    |     raise InvalidBufferPos(f'Pos bigger than buffer: {e_pos} > {self.buf_len}')
[2022-01-25 04:50:45,429] [sml.device.ttyUSB0     ] ERROR    | smllib.sml_frame.InvalidBufferPos: Pos bigger than buffer: 941 > 219
[2022-01-25 04:50:45,430] [sml.device.ttyUSB0     ] INFO     | ERROR
[2022-01-25 04:50:45,434] [sml.serial             ] INFO     | Port /dev/ttyUSB0 was closed
[2022-01-25 04:50:45,434] [sml.device.ttyUSB0     ] INFO     | PORT_CLOSED
[2022-01-25 04:50:45,749] [asyncio                ] ERROR    | Task was destroyed but it is pending!
task: <Task pending name='Task-124577' coro=<stop_loop() done, defined at /opt/sml2mqtt/venv/lib/python3.8/site-packages/sml2mqtt/_signals.py:10> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x75b69550>()]>>

[2022-01-25 17:17:58,573] [sml.device.ttyUSB0     ] INFO     | PORT_OPENED
[2022-01-25 17:17:59,047] [sml.device.ttyUSB0     ] INFO     | OK

[2022-01-25 23:37:32,852] [sml.device.ttyUSB0     ] ERROR    | Traceback (most recent call last):
[2022-01-25 23:37:32,852] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/sml2mqtt/sml_device.py", line 90, in read
[2022-01-25 23:37:32,853] [sml.device.ttyUSB0     ] ERROR    |     for sml_obj in frame.get_obis():
[2022-01-25 23:37:32,853] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 112, in get_obis
[2022-01-25 23:37:32,853] [sml.device.ttyUSB0     ] ERROR    |     self._parse_msg(data)
[2022-01-25 23:37:32,854] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 101, in _parse_msg
[2022-01-25 23:37:32,854] [sml.device.ttyUSB0     ] ERROR    |     self._parse_msg(v)
[2022-01-25 23:37:32,854] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 99, in _parse_msg
[2022-01-25 23:37:32,855] [sml.device.ttyUSB0     ] ERROR    |     parent_obj[i] = v = self.get_value()
[2022-01-25 23:37:32,855] [sml.device.ttyUSB0     ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.8/site-packages/smllib/sml_frame.py", line 62, in get_value
[2022-01-25 23:37:32,855] [sml.device.ttyUSB0     ] ERROR    |     raise InvalidBufferPos(f'Pos bigger than buffer: {e_pos} > {self.buf_len}')
[2022-01-25 23:37:32,856] [sml.device.ttyUSB0     ] ERROR    | smllib.sml_frame.InvalidBufferPos: Pos bigger than buffer: 941 > 219
[2022-01-25 23:37:32,856] [sml.device.ttyUSB0     ] INFO     | ERROR
[2022-01-25 23:37:32,859] [sml.serial             ] INFO     | Port /dev/ttyUSB0 was closed
[2022-01-25 23:37:32,859] [sml.device.ttyUSB0     ] INFO     | PORT_CLOSED
[2022-01-25 23:37:33,170] [asyncio                ] ERROR    | Task was destroyed but it is pending!
task: <Task pending name='Task-181350' coro=<stop_loop() done, defined at /opt/sml2mqtt/venv/lib/python3.8/site-packages/sml2mqtt/_signals.py:10> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x75ba57f0>()]>>
````

So the tool logs show PORT_OPENER & OK and then a few hours later the traceback gets dumped without any further information.

**Comment by mrumpf** [comment]
Wouldn't it be possible to just skip the current frame and continue with the next one instead of stopping the execution completely in case of an error?

**Comment by spacemanspiff2007** [comment]
> Wouldn't it be possible to just skip the current frame and continue with the next one instead of stopping the execution completely in case of a parsing error?

I've already fixed the issue in the underlying library but I have yet to port the changes to sml2mqtt.
Maybe over the course of next week I'll find the time to do it.

**Comment by mrumpf** [comment]
Great. Thank you! The log somehow indicates that the port is opened again after it was closed but no data is read anymore. When I restart the service with "systemctl restart sml2mqtt" it works again. 
So I see 2 issues, one is the parsing error which raises an exception and the second one is that reopening the port does not work anymore. Unfortunately I have no idea why the serial port read does not return data anymore.

**Comment by spacemanspiff2007** [comment]
@mrumpf 
Do you still experience the issue?

**Comment by steigerbalett** [comment]
@spacemanspiff2007:
The issue is still present in my system. I have to restart sml2mqtt continuous

**Comment by spacemanspiff2007** [comment]
Which version are you running and can you post the logfile please?

**Comment by steigerbalett** [comment]
Logfile is 104 MB :-D 
Most is like: 
`{"log":"[2022-06-02 18:07:24,436] [sml.mqtt               ] ERROR    | Error while publishing to sml2mqtt//dev/ttyUSB0/0100100700ff: [code:4] The client is not currently connected. (MqttCodeError)\n","stream":"stdout","time":"2022-06-02T18:07:24.437016734Z"}`

But I recogniced, that i am still on Version 1.0.1 -  so I have to update and reverify the problem:
`{"log":"[2022-06-02 08:34:37,316] [sml                    ] INFO     | Starting V1.0.1\n","stream":"stdout","time":"2022-06-02T08:34:37.317124138Z"}`

**Comment by steigerbalett** [comment]
The Problem still exist in my setup (see attached logfile snippet):

[2022-06-08 01:33:26,962] [sml.mqtt               ] ERROR    | Error while publishing to sml2mqtt//dev/ttyUSB0/0100100700ff: [code:4] The client is not currently connected. (MqttCodeError)
[2022-06-08 01:33:27,958] [sml.ttyUSB0            ] ERROR    | Received Frame
[2022-06-08 01:33:27,959] [sml.ttyUSB0            ] ERROR    |  -> b'7605065850a66200620072630101760107ffffffffffff05021d70370b0a014c475a0003403b4972620165021d7707016326de007605065850a762006200726307017707ffffffffffff0b0a014c475a0003403b49070100620affff72620165021d770775770701006032010101010101044c475a0177070100600100ff010101010b0a014c475a0003403b490177070100010800ff65001c010472620165021d7707621e52ff690000000003152c450177070100020800ff0172620165021d7707621e52ff6900000000000000000177070100100700ff0101621b52005900000000000000fb010101637264007605065850a862006200726302017101631c8c00'
[2022-06-08 01:33:27,966] [sml.ttyUSB0            ] ERROR    | Traceback (most recent call last):
[2022-06-08 01:33:27,967] [sml.ttyUSB0            ] ERROR    |   File "/usr/lib/python3.9/site-packages/sml2mqtt/device/sml_device.py", line 119, in serial_data_read
[2022-06-08 01:33:27,967] [sml.ttyUSB0            ] ERROR    |     await self.process_frame(frame)
[2022-06-08 01:33:27,968] [sml.ttyUSB0            ] ERROR    |   File "/usr/lib/python3.9/site-packages/sml2mqtt/device/sml_device.py", line 151, in process_frame
[2022-06-08 01:33:27,969] [sml.ttyUSB0            ] ERROR    |     for sml_obj in frame.get_obis():
[2022-06-08 01:33:27,970] [sml.ttyUSB0            ] ERROR    |   File "/usr/lib/python3.9/site-packages/smllib/sml_frame.py", line 124, in get_obis
[2022-06-08 01:33:27,970] [sml.ttyUSB0            ] ERROR    |     ret.append(self.build_ctx[SmlListEntry].build(data, self.build_ctx))
[2022-06-08 01:33:27,971] [sml.ttyUSB0            ] ERROR    |   File "/usr/lib/python3.9/site-packages/smllib/builder/list_entry.py", line 14, in build
[2022-06-08 01:33:27,972] [sml.ttyUSB0            ] ERROR    |     ret = super().build(obj, classes)    # type: SmlListEntry
[2022-06-08 01:33:27,972] [sml.ttyUSB0            ] ERROR    |   File "/usr/lib/python3.9/site-packages/smllib/builder/_builder.py", line 40, in build
[2022-06-08 01:33:27,973] [sml.ttyUSB0            ] ERROR    |     raise WrongValueType(f'{value} ({type(value)}) != {field.type}')
[2022-06-08 01:33:27,974] [sml.ttyUSB0            ] ERROR    | smllib.errors.WrongValueType: 065850a7 (<class 'str'>) != (<class 'int'>, <class 'NoneType'>)
[2022-06-08 01:33:27,975] [sml.ttyUSB0.status     ] INFO     | ERROR
[2022-06-08 01:33:27,977] [sml.mqtt               ] ERROR    | Error while publishing to sml2mqtt//dev/ttyUSB0/status: [code:4] The client is not currently connected. (MqttCodeError)
[2022-06-08 01:33:27,979] [sml.serial             ] INFO     | Port /dev/ttyUSB0 was closed
[2022-06-08 01:33:27,980] [sml.ttyUSB0.status     ] INFO     | PORT_CLOSED
[2022-06-08 01:33:27,983] [sml                    ] INFO     | Shutting down ...
[2022-06-08 01:33:27,984] [asyncio                ] ERROR    | Task exception was never retrieved
future: <Task finished name='Task-409736' coro=<do_shutdown() done, defined at /usr/lib/python3.9/site-packages/sml2mqtt/__shutdown__.py:51> exception=MqttCodeError('Could not disconnect')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sml2mqtt/__shutdown__.py", line 61, in do_shutdown
    await sml2mqtt.mqtt.disconnect()
  File "/usr/lib/python3.9/site-packages/sml2mqtt/mqtt/mqtt.py", line 34, in disconnect
    await mqtt.disconnect()
  File "/usr/lib/python3.9/site-packages/asyncio_mqtt/client.py", line 240, in disconnect
    raise MqttCodeError(rc, "Could not disconnect")
asyncio_mqtt.error.MqttCodeError: [code:4] The client is not currently connected.

---
[Logfile_sml2mqtt_03.log](https://github.com/spacemanspiff2007/sml2mqtt/files/8883486/Logfile_sml2mqtt_03.log)

**Comment by spacemanspiff2007** [comment]
Could you try again with 1.2.0? I added a fallback there.

**Comment by steigerbalett** [comment]
Still up and running 👍 

[2022-06-14 12:58:08,395] [sml                    ] INFO     | Starting V1.2.0
[2022-06-14 12:58:08,508] [sml.ttyUSB0.status     ] INFO     | PORT_OPENED
[2022-06-14 12:58:09,117] [sml.ttyUSB0.status     ] INFO     | OK
[2022-06-14 21:24:01,621] [sml.ttyUSB0            ] INFO     | get_obis failed - try parsing frame
[2022-06-15 15:36:18,695] [sml.ttyUSB0            ] INFO     | get_obis failed - try parsing frame
[2022-06-15 19:55:39,955] [sml.ttyUSB0            ] INFO     | get_obis failed - try parsing frame

**Comment by spacemanspiff2007** [comment]
As you can see in the log the fallback is working.
If you experience any more issues feel free to open another issue.
